site_name: Simon Dückert's Tweetbook
site_url: https://simondueckert.github.io/tweetbook
docs_dir: src
site_dir: docs

nav:
    - Willkommen: index.md
    - 2007:
        - September: 2007-09-01-Tweet-Archive-2007-09.md
        - Oktober: 2007-10-01-Tweet-Archive-2007-10.md
        - Dezember: 2007-12-01-Tweet-Archive-2007-12.md
    - 2008:
        - Januar: 2008-01-01-Tweet-Archive-2008-01.md
        - April: 2008-04-01-Tweet-Archive-2008-04.md
        - Juli: 2008-07-01-Tweet-Archive-2008-07.md
        - August: 2008-08-01-Tweet-Archive-2008-08.md
        - September: 2008-09-01-Tweet-Archive-2008-09.md
        - Oktober: 2008-10-01-Tweet-Archive-2008-10.md
        - November: 2008-11-01-Tweet-Archive-2008-11.md
    - 2009:
        - Februar: 2009-02-01-Tweet-Archive-2009-02.md
        - März: 2009-03-01-Tweet-Archive-2009-03.md
        - April: 2009-04-01-Tweet-Archive-2009-04.md
        - Mai: 2009-05-01-Tweet-Archive-2009-05.md
        - Juni: 2009-06-01-Tweet-Archive-2009-06.md
        - Juli: 2009-07-01-Tweet-Archive-2009-07.md
        - August: 2009-08-01-Tweet-Archive-2009-08.md
        - September: 2009-09-01-Tweet-Archive-2009-09.md
        - Oktober: 2009-10-01-Tweet-Archive-2009-10.md
        - November: 2009-11-01-Tweet-Archive-2009-11.md
        - Dezember: 2009-12-01-Tweet-Archive-2009-12.md
    - 2010:
        - Januar: 2010-01-01-Tweet-Archive-2010-01.md
        - Februar: 2010-02-01-Tweet-Archive-2010-02.md
        - März: 2010-03-01-Tweet-Archive-2010-03.md
        - April: 2010-04-01-Tweet-Archive-2010-04.md
        - Mai: 2010-05-01-Tweet-Archive-2010-05.md
        - Juni: 2010-06-01-Tweet-Archive-2010-06.md
        - Juli: 2010-07-01-Tweet-Archive-2010-07.md
        - August: 2010-08-01-Tweet-Archive-2010-08.md
        - September: 2010-09-01-Tweet-Archive-2010-09.md
        - Oktober: 2010-10-01-Tweet-Archive-2010-10.md
        - November: 2010-11-01-Tweet-Archive-2010-11.md
        - Dezember: 2010-12-01-Tweet-Archive-2010-12.md
    - 2011:
        - Januar: 2011-01-01-Tweet-Archive-2011-01.md
        - Februar: 2011-02-01-Tweet-Archive-2011-02.md
        - März: 2011-03-01-Tweet-Archive-2011-03.md
        - April: 2011-04-01-Tweet-Archive-2011-04.md
        - Mai: 2011-05-01-Tweet-Archive-2011-05.md
        - Juni: 2011-06-01-Tweet-Archive-2011-06.md
        - Juli: 2011-07-01-Tweet-Archive-2011-07.md
        - August: 2011-08-01-Tweet-Archive-2011-08.md
        - September: 2011-09-01-Tweet-Archive-2011-09.md
        - Oktober: 2011-10-01-Tweet-Archive-2011-10.md
        - November: 2011-11-01-Tweet-Archive-2011-11.md
        - Dezember: 2011-12-01-Tweet-Archive-2011-12.md
    - 2012:
        - Januar: 2012-01-01-Tweet-Archive-2012-01.md
        - Februar: 2012-02-01-Tweet-Archive-2012-02.md
        - März: 2012-03-01-Tweet-Archive-2012-03.md
        - April: 2012-04-01-Tweet-Archive-2012-04.md
        - Mai: 2012-05-01-Tweet-Archive-2012-05.md
        - Juni: 2012-06-01-Tweet-Archive-2012-06.md
        - Juli: 2012-07-01-Tweet-Archive-2012-07.md
        - August: 2012-08-01-Tweet-Archive-2012-08.md
        - September: 2012-09-01-Tweet-Archive-2012-09.md
        - Oktober: 2012-10-01-Tweet-Archive-2012-10.md
        - November: 2012-11-01-Tweet-Archive-2012-11.md
        - Dezember: 2012-12-01-Tweet-Archive-2012-12.md
    - 2013:
        - Januar: 2013-01-01-Tweet-Archive-2013-01.md
        - Februar: 2013-02-01-Tweet-Archive-2013-02.md
        - März: 2013-03-01-Tweet-Archive-2013-03.md
        - April: 2013-04-01-Tweet-Archive-2013-04.md
        - Mai: 2013-05-01-Tweet-Archive-2013-05.md
        - Juni: 2013-06-01-Tweet-Archive-2013-06.md
        - Juli: 2013-07-01-Tweet-Archive-2013-07.md
        - August: 2013-08-01-Tweet-Archive-2013-08.md
        - September: 2013-09-01-Tweet-Archive-2013-09.md
        - Oktober: 2013-10-01-Tweet-Archive-2013-10.md
        - November: 2013-11-01-Tweet-Archive-2013-11.md
        - Dezember: 2013-12-01-Tweet-Archive-2013-12.md
    - 2014:
        - Januar: 2014-01-01-Tweet-Archive-2014-01.md
        - Februar: 2014-02-01-Tweet-Archive-2014-02.md
        - März: 2014-03-01-Tweet-Archive-2014-03.md
        - April: 2014-04-01-Tweet-Archive-2014-04.md
        - Mai: 2014-05-01-Tweet-Archive-2014-05.md
        - Juni: 2014-06-01-Tweet-Archive-2014-06.md
        - Juli: 2014-07-01-Tweet-Archive-2014-07.md
        - August: 2014-08-01-Tweet-Archive-2014-08.md
        - September: 2014-09-01-Tweet-Archive-2014-09.md
        - Oktober: 2014-10-01-Tweet-Archive-2014-10.md
        - November: 2014-11-01-Tweet-Archive-2014-11.md
        - Dezember: 2014-12-01-Tweet-Archive-2014-12.md
    - 2015:
        - Januar: 2015-01-01-Tweet-Archive-2015-01.md
        - Februar: 2015-02-01-Tweet-Archive-2015-02.md
        - März: 2015-03-01-Tweet-Archive-2015-03.md
        - April: 2015-04-01-Tweet-Archive-2015-04.md
        - Mai: 2015-05-01-Tweet-Archive-2015-05.md
        - Juni: 2015-06-01-Tweet-Archive-2015-06.md
        - Juli: 2015-07-01-Tweet-Archive-2015-07.md
        - August: 2015-08-01-Tweet-Archive-2015-08.md
        - September: 2015-09-01-Tweet-Archive-2015-09.md
        - Oktober: 2015-10-01-Tweet-Archive-2015-10.md
        - November: 2015-11-01-Tweet-Archive-2015-11.md
        - Dezember: 2015-12-01-Tweet-Archive-2015-12.md
    - 2016:
        - Januar: 2016-01-01-Tweet-Archive-2016-01.md
        - Februar: 2016-02-01-Tweet-Archive-2016-02.md
        - März: 2016-03-01-Tweet-Archive-2016-03.md
        - April: 2016-04-01-Tweet-Archive-2016-04.md
        - Mai: 2016-05-01-Tweet-Archive-2016-05.md
        - Juni: 2016-06-01-Tweet-Archive-2016-06.md
        - Juli: 2016-07-01-Tweet-Archive-2016-07.md
        - August: 2016-08-01-Tweet-Archive-2016-08.md
        - September: 2016-09-01-Tweet-Archive-2016-09.md
        - Oktober: 2016-10-01-Tweet-Archive-2016-10.md
        - November: 2016-11-01-Tweet-Archive-2016-11.md
        - Dezember: 2016-12-01-Tweet-Archive-2016-12.md
    - 2017:
        - Januar: 2017-01-01-Tweet-Archive-2017-01.md
        - Februar: 2017-02-01-Tweet-Archive-2017-02.md
        - März: 2017-03-01-Tweet-Archive-2017-03.md
        - April: 2017-04-01-Tweet-Archive-2017-04.md
        - Mai: 2017-05-01-Tweet-Archive-2017-05.md
        - Juni: 2017-06-01-Tweet-Archive-2017-06.md
        - Juli: 2017-07-01-Tweet-Archive-2017-07.md
        - August: 2017-08-01-Tweet-Archive-2017-08.md
        - September: 2017-09-01-Tweet-Archive-2017-09.md
        - Oktober: 2017-10-01-Tweet-Archive-2017-10.md
        - November: 2017-11-01-Tweet-Archive-2017-11.md
        - Dezember: 2017-12-01-Tweet-Archive-2017-12.md
    - 2018:
        - Januar: 2018-01-01-Tweet-Archive-2018-01.md
        - Februar: 2018-02-01-Tweet-Archive-2018-02.md
        - März: 2018-03-01-Tweet-Archive-2018-03.md
        - April: 2018-04-01-Tweet-Archive-2018-04.md
        - Mai: 2018-05-01-Tweet-Archive-2018-05.md
        - Juni: 2018-06-01-Tweet-Archive-2018-06.md
        - Juli: 2018-07-01-Tweet-Archive-2018-07.md
        - August: 2018-08-01-Tweet-Archive-2018-08.md
        - September: 2018-09-01-Tweet-Archive-2018-09.md
        - Oktober: 2018-10-01-Tweet-Archive-2018-10.md
        - November: 2018-11-01-Tweet-Archive-2018-11.md
        - Dezember: 2018-12-01-Tweet-Archive-2018-12.md
    - 2019:
        - Januar: 2019-01-01-Tweet-Archive-2019-01.md
        - Februar: 2019-02-01-Tweet-Archive-2019-02.md
        - März: 2019-03-01-Tweet-Archive-2019-03.md
        - April: 2019-04-01-Tweet-Archive-2019-04.md
        - Mai: 2019-05-01-Tweet-Archive-2019-05.md
        - Juni: 2019-06-01-Tweet-Archive-2019-06.md
        - Juli: 2019-07-01-Tweet-Archive-2019-07.md
        - August: 2019-08-01-Tweet-Archive-2019-08.md
        - September: 2019-09-01-Tweet-Archive-2019-09.md
        - Oktober: 2019-10-01-Tweet-Archive-2019-10.md
        - November: 2019-11-01-Tweet-Archive-2019-11.md
        - Dezember: 2019-12-01-Tweet-Archive-2019-12.md
    - 2020:
        - Januar: 2020-01-01-Tweet-Archive-2020-01.md
        - Februar: 2020-02-01-Tweet-Archive-2020-02.md
        - März: 2020-03-01-Tweet-Archive-2020-03.md
        - April: 2020-04-01-Tweet-Archive-2020-04.md
        - Mai: 2020-05-01-Tweet-Archive-2020-05.md
        - Juni: 2020-06-01-Tweet-Archive-2020-06.md
        - Juli: 2020-07-01-Tweet-Archive-2020-07.md
        - August: 2020-08-01-Tweet-Archive-2020-08.md
        - September: 2020-09-01-Tweet-Archive-2020-09.md
        - Oktober: 2020-10-01-Tweet-Archive-2020-10.md
        - November: 2020-11-01-Tweet-Archive-2020-11.md
        - Dezember: 2020-12-01-Tweet-Archive-2020-12.md
    - 2021:
        - Januar: 2021-01-01-Tweet-Archive-2021-01.md
        - Februar: 2021-02-01-Tweet-Archive-2021-02.md
        - März: 2021-03-01-Tweet-Archive-2021-03.md
        - April: 2021-04-01-Tweet-Archive-2021-04.md
        - Mai: 2021-05-01-Tweet-Archive-2021-05.md
        - Juni: 2021-06-01-Tweet-Archive-2021-06.md
        - Juli: 2021-07-01-Tweet-Archive-2021-07.md
        - August: 2021-08-01-Tweet-Archive-2021-08.md
        - September: 2021-09-01-Tweet-Archive-2021-09.md
        - Oktober: 2021-10-01-Tweet-Archive-2021-10.md
        - November: 2021-11-01-Tweet-Archive-2021-11.md
        - Dezember: 2021-12-01-Tweet-Archive-2021-12.md
    - 2022:
        - Januar: 2022-01-01-Tweet-Archive-2022-01.md
        - Februar: 2022-02-01-Tweet-Archive-2022-02.md
        - März: 2022-03-01-Tweet-Archive-2022-03.md
        - April: 2022-04-01-Tweet-Archive-2022-04.md
        - Mai: 2022-05-01-Tweet-Archive-2022-05.md
        - Juni: 2022-06-01-Tweet-Archive-2022-06.md
        - Juli: 2022-07-01-Tweet-Archive-2022-07.md
        - August: 2022-08-01-Tweet-Archive-2022-08.md
        - September: 2022-09-01-Tweet-Archive-2022-09.md
        - Oktober: 2022-10-01-Tweet-Archive-2022-10.md
        - November: 2022-11-01-Tweet-Archive-2022-11.md
    - The End: https://twitter.com/SimonDueckert/status/1603006808997912578?s=20&t=kHGEE0yC9-KXE6PDK9tgjg

theme:
    name: 'material'
    palette:
      primary: teal
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

repo_name: 'simondueckert/tweetbook'
repo_url: 'https://github.com/simondueckert/tweetbook'

extra:
    homepage: https://blog.dueckert.eu
    social:
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/simondueckert'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/in/simondueckert/'
        - icon: fontawesome/brands/github
          link: 'https://github.com/simondueckert'

    plugins:
      - search
